spring.application.name=backend
# --- CONEXIÓN A SQL SERVER ---
# Asegúrate de que el puerto sea 1433 (es el por defecto) y el nombre de la DB coincida
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=borrador_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
# IMPORTANTE: Cambia esto por la contraseña que le pusiste al usuario 'sa' cuando instalaste SQL Server
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# Muestra en la consola de IntelliJ las consultas SQL que Spring hace por detrás (para debugear)
spring.jpa.show-sql=true
# le decimos a Hibernate (Spring) que NO intente crear ni modificar las tablas por su cuenta.
spring.jpa.hibernate.ddl-auto=none